name: gpt_flutter
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.1.3
  chat_gpt_sdk: ^2.0.2
  speech_to_text: ^6.1.1
  flutter_tts: ^3.8.3
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/talk.json
    - assets/answer.json
    - assets/textbar.json
    - assets/Robotka_trans.gif
    - assets/talking.json
    - assets/new/StarTalkLogoTrans.gif
    - assets/new/TalkBackground.gif

  fonts:
    - family: BungeeSpice
      fonts:
        - asset: assets/BungeeSpice-Regular.ttf
